name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # or change to your branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or your project's version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.1.0
        with:
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
          project_id: amelito-alcuitasjr
